In [16]:
import numpy as np
arr = np.arange(1,10,2)
print("Elements of array: ", arr)
arr1 = arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ", arr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


In [18]:
arr1 = np.arange(5)
print("Array arr11: ", arr1)
print("Element at index 0 of arri is: ", arr1[0])
print("Element at index 1 of ari is: ", arr1[1])


Array arr11:  [0 1 2 3 4]
Element at index 0 of arri is:  0
Element at index 1 of ari is:  1


In [20]:
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print(arr1)
print("Element at each row and eth column of arr1 is: ", arr1[0,0])
print("Element at 1st row and 2nd column of arr1 is: ", arr1[1,2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at each row and eth column of arr1 is:  0
Element at 1st row and 2nd column of arr1 is:  6


In [22]:
arr = np.arange(12)
arr1 = arr.reshape(2,2,3)
print(arr1)
print("Element: ", arr1[1,0,2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element:  8


In [24]:
arr = np.arange(6)
print(arr)
print("Sliced eleent of array: ", arr[1:5])

[0 1 2 3 4 5]
Sliced eleent of array:  [1 2 3 4]


In [26]:
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print(arr1)
print("Element of 1st row and 1st column upto last column  \n", arr1[1:,1:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element of 1st row and 1st column upto last column  
 [[ 5  6  7]
 [ 9 10 11]]


In [28]:
import numpy as np

tdarr = np.array([[1,2,3],[4,5,6]])
print (tdarr)

[[1 2 3]
 [4 5 6]]


In [30]:
threed = np.array([[[1,2],[3,4]],
                   [[5,6],[5,3]],
                   [[3,5],[3,33]]])
print(threed)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 5  3]]

 [[ 3  5]
  [ 3 33]]]


In [32]:
print(tdarr.ndim)

2


In [34]:
print(threed.ndim)

3


In [51]:
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print(arr1)
print("\n")
print( arr1[2:,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 9 10]]


In [55]:
print( arr1[0:,1])

[1 5 9]


In [63]:
print( arr1[1:,0:2])

[[4 5]
 [8 9]]


In [65]:
print( arr1[1:,2:])

[[ 6  7]
 [10 11]]


In [67]:
print( arr1[0:,3])

[ 3  7 11]


In [69]:
print( arr1[0,1:4])

[1 2 3]


In [80]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

In [85]:
print("first array:")
print(a)
print('\n')

print("Second array:")
print(b)

first array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


In [90]:
print ("First array + Seconf array")
print(a+b)

First array + Seconf array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [96]:
a = np.array([('Sana', 2, 21.0), ('Mansi', 7,29.0)],
             dtype=[('name', (np.str_, 10)),
                    ('age', np.int32),
                    ('weight', np.float64)])
print(a)

[('Sana', 2, 21.) ('Mansi', 7, 29.)]


In [118]:
arr = np.arange(1,10,2)
print(arr)
mean = np.mean(arr)
median = np.median(arr)
range = np.ptp(arr)
std = np.std(arr)
var = np.var(arr)
print(mean)
print(median)
print(range)
print(std)
print(var)

[1 3 5 7 9]
5.0
5.0
8
2.8284271247461903
8.0


In [120]:
arr = np.arange(0,10)

In [122]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [124]:
print (arr+arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [126]:
print (arr*arr)

[ 0  1  4  9 16 25 36 49 64 81]
