In [30]:
import numpy as np

my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [32]:
np.array(my_list)

array([1, 2, 3])

In [34]:
my_matrix =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr1 = np.array (42)
print(arr1)


42


In [40]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)

[1 2 3 4 5]


In [42]:
arr3 = np.array ([[1, 2, 3], [4, 5, 6]])
print(arr3)


[[1 2 3]
 [4 5 6]]


In [44]:
arr4 = np.array([[[2,17], [45, 78]],
                 [[88, 92], [60, 76]],
                 [[76, 33], [20, 18]]])
print("CreTE 3D array : ", arr4)


CreTE 3D array :  [[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


In [46]:
a = np.array([1, 2, 3, 4, 5])
np.save('outfile', a)

In [48]:
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


In [56]:
a1 = np.array([1, 2, 3, 4, 5])
np.savetxt('out.txt', a1)
b1 = np.loadtxt('out.txt')
print(b1)

[1. 2. 3. 4. 5.]
